name: sqlite_demo
description: A sqlite Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  floor: ^1.3.0
  shared_preferences: any
  miniplayer: ^1.0.0+2
  provider: ^6.0.3
  flutter_riverpod: ^0.13.1+1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.3.0
  build_runner: ^2.1.2

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
